### PR TITLE
Add Permalink settings page.

### PR DESCRIPTION
**Pull request by felixarntz**
This is a PR to address #21.

I made sure things work correctly functionality-wise (this is more important for the UI anyways, and will get a closer review related to code and functionality over the course of time). Can you review the markup @afercia? I noticed that the permalink structure text field is currently without a label. Maybe a `screen-reader-text` should be added for now?

### CODE REVIEW

**Comment by afercia** [comment]
@felixarntz thanks! Re: the custom structure field, I think the best option would be doing the same thing we're doing in General Settings for the date/time custom formats: a visible label is always the best option:

screen shot 2017-06-09 at 19 03 33

Text could be something like:
`Custom: enter a custom structure in the field below`
`Custom structure:`

Couple notes about things we should address later:
- the examples (the `<code>` stuff) are terrible when announced by screen readers, we should try to thing at some improved experience, even if the sample URLs have to be announced
- the labels for radio buttons: currently there's some inconsistency across the plugin: here are explicitly associated and that's good, while in General Settings are a mix, less good :)
Example from General Settings (not recommended):
```
<label for="date_format-01">
<span class="date-time-text format-i18n">June 9, 2017</span>
<code>F j, Y</code>
</label>
```

**Comment by afercia** [comment]
About the "custom" field here and in General settings, forgot to mention: Ideally it shouldn't be part of the radio buttons fieldset. I guess it would be a bit tricky, but we should try to find a way to move it outside of the fieldset. Something for later :)

**Review by afercia — APPROVED** [review]
Gooo! (see comments btw!)

**Comment by felixarntz** [comment]
@afercia Adjusting the permalink structure field to the changes you proposed is a bit more complicated. I'd rather open a ticket to deal with all of it properly than doing complex changes here we may need to revert later. For now I just added a `.screen-reader-text` label so that the text field at least has a label.

**Pull request merged**
